from __future__ import annotations
from collections.abc import Callable
from functools import wraps
from typing import Generic, TypeVar, Unpack

from httpx import Client, AsyncClient, Response, QueryParams
from urllib.parse import urljoin

from .schema import *
_S = TypeVar('_S')

        
def make_endpoint(endpoint: str, method: Literal['GET', 'POST', 'PATCH', 'DELETE']):
    def _inner(func: Callable[..., _S]) -> Callable[..., _S]:
        

class _Endpoint:
    def __init__(self, client: Client) -> None:
        self.client = client
    
class Activity(_Endpoint):
    
    @make_endpoint('/activity/{id}')
    def get_activity(self, id: int, **params: Any) -> DirectusActivity: ...
    
    @make_endpoint('/activity')
    def get_activities(self) -> list[DirectusActivity]: ...

class Assets(_Endpoint):
    def get_asset() -> Response: ...
    
class Auth(_Endpoint): ...

class Collections(_Endpoint): ...

class Comments(_Endpoint): ...

class Dashboards(_Endpoint): ...

class Extensions(_Endpoint): ...

class Fields(_Endpoint): ...

class Files(_Endpoint): ...

class Folders(_Endpoint): ...

class Items(_Endpoint): ...

class Metrics(_Endpoint): ...

class Notifications(_Endpoint): ...

class Operations(_Endpoint): ...

class Panels(_Endpoint): ...

class Permissions(_Endpoint): ...

class Policies(_Endpoint): ...

class Presets(_Endpoint): ...

class Relations(_Endpoint): ...

class Revisions(_Endpoint): ...

class Roles(_Endpoint): ...

class Schema(_Endpoint): ...

class Server(_Endpoint): ...

class Settings(_Endpoint): ...

class Shares(_Endpoint): ...

class Translations(_Endpoint): ...

class Users(_Endpoint): ...

class Utils(_Endpoint): ...

class Versions(_Endpoint): ...