from __future__ import annotations
from typing import Any, Literal

FilterOpts = Literal[
    '_eq',
    '_neq',
    '_lt',
    '_lte',
    '_gt',
    '_gte',
    '_in',
    '_nin',
    '_null',
    '_nnull',
    '_contains',
    '_ncontains',
    '_icontains',
    '_nicontains',
    '_starts_with',
    '_istarts_with',
    '_nstarts_with',
    '_nistarts_with',
    '_ends_with',
    '_iends_with',
    '_nends_with',
    '_niends_with',
    '_between',
    '_nbetween',
    '_empty',
    '_nempty',
    '_intersects',
    '_nintersects',
    '_intersects_bbox',
    '_nintersects_bbox',
    '_regex',
    '_some',
    '_none',
]

def parameters(
    id: int | str | None=None,
    collection: str | None=None,
    search: str | None=None,
    page: int | None=None,
    offset: int | None=None,
    sort: list[str] | None=None,
    meta: str | None=None,
    limit: int | None=None,
    filter: dict[str, dict[FilterOpts, Any]] | None=None,
    fields: list[str] | None=None,
    export: Literal['csv', 'json', 'xml', 'yaml'] | None=None,
    version: str | None=None,
    backlink: bool | None=True,
)
